/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Map;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import services.InscriptionService;

/**
 *
 * @author hamza
 */
public class ByCompetitionName extends javax.swing.JInternalFrame {

    //InscriptionService is;
    /**
     * Creates new form ByCompetitionName
     */
public ByCompetitionName() {
    super("Student % by Competition", true, true, true, true);
    setSize(1200, 900);
    setFrameIcon(new ImageIcon(getClass().getResource("/icons/balls.png")));

    // Fetch data from service
    InscriptionService service = new InscriptionService();
    Map<String, Integer> dataMap = service.getStudentCountByCompetition();

    DefaultPieDataset dataset = new DefaultPieDataset();
    for (Map.Entry<String, Integer> entry : dataMap.entrySet()) {
        dataset.setValue(entry.getKey(), entry.getValue());
    }

    // Create chart
    JFreeChart chart = ChartFactory.createPieChart(
            "Student % by Competition",
            dataset,
            true,
            true,
            false
    );

    PiePlot plot = (PiePlot) chart.getPlot();

    // ✅ Show percentage in labels
    PieSectionLabelGenerator labelGenerator = new org.jfree.chart.labels.StandardPieSectionLabelGenerator(
            "{0} ({2})",
            NumberFormat.getNumberInstance(), new DecimalFormat("0.0%")
    );
    plot.setLabelGenerator(labelGenerator);

    // 🎨 Custom colors
    plot.setSectionPaint("Football", new Color(0x000000));
    plot.setSectionPaint("Basket-ball", new Color(0x2196F3));
    plot.setSectionPaint("Gymnastique", new Color(0xFF9800));
    plot.setSectionPaint("Saut en longeur", new Color(0xfffe00));
    plot.setSectionPaint("Hand-ball", new Color(0xb1ff00));
    plot.setSectionPaint("Volley-ball", new Color(0xb1ff00));
    plot.setSectionPaint("Badminton", new Color(0xff005e));

    ChartPanel chartPanel = new ChartPanel(chart);
    setContentPane(chartPanel);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1095, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
