/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author hamza
 */
public class MDIApplication extends javax.swing.JFrame {

    /**
     * Creates new form MDIApplication
     */
    public MDIApplication() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //setUndecorated(true);
        UIManager.put("InternalFrame.border", BorderFactory.createLineBorder(Color.BLUE, 3));
        UIManager.put("InternalFrame.activeTitleBackground", Color.DARK_GRAY);
        UIManager.put("InternalFrame.inactiveTitleBackground", Color.LIGHT_GRAY);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/balls.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        CompetitionMenuItem = new javax.swing.JMenuItem();
        EtudiantMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        listeMenuItem = new javax.swing.JMenu();
        listeEtdMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        byName = new javax.swing.JMenuItem();
        byType = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        CompetitionMenuItem.setMnemonic('o');
        CompetitionMenuItem.setText("Compétitions");
        CompetitionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompetitionMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(CompetitionMenuItem);

        EtudiantMenuItem.setMnemonic('s');
        EtudiantMenuItem.setText("Etudiants");
        EtudiantMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EtudiantMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(EtudiantMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        listeMenuItem.setMnemonic('e');
        listeMenuItem.setText("Filtage");

        listeEtdMenuItem.setMnemonic('d');
        listeEtdMenuItem.setText("Etudiants par Compétition");
        listeEtdMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeEtdMenuItemActionPerformed(evt);
            }
        });
        listeMenuItem.add(listeEtdMenuItem);

        menuBar.add(listeMenuItem);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Statistiques");

        byName.setMnemonic('c');
        byName.setText("Taux par Compétition");
        byName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byNameActionPerformed(evt);
            }
        });
        helpMenu.add(byName);

        byType.setMnemonic('a');
        byType.setText("Taux par type de Compétition");
        byType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byTypeActionPerformed(evt);
            }
        });
        helpMenu.add(byType);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void CompetitionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompetitionMenuItemActionPerformed
        // TODO add your handling code here:
        CompetitionForm cf = new CompetitionForm();
        desktopPane.add(cf);
        int x = (desktopPane.getWidth() - cf.getWidth()) / 2;
        int y = (desktopPane.getHeight() - cf.getHeight()) / 2;
        cf.setLocation(Math.max(x, 0), Math.max(y, 0));
        cf.setVisible(true);
    }//GEN-LAST:event_CompetitionMenuItemActionPerformed

    private void listeEtdMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeEtdMenuItemActionPerformed
        ListeEtdForm lef = new ListeEtdForm();
        desktopPane.add(lef);
        int x = (desktopPane.getWidth() - lef.getWidth()) / 2;
        int y = (desktopPane.getHeight() - lef.getHeight()) / 2;
        lef.setLocation(Math.max(x, 0), Math.max(y, 0));
        lef.setVisible(true);
    }//GEN-LAST:event_listeEtdMenuItemActionPerformed

    private void EtudiantMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EtudiantMenuItemActionPerformed
        EtudiantForm ef = new EtudiantForm();
        desktopPane.add(ef);
        int x = (desktopPane.getWidth() - ef.getWidth()) / 2;
        int y = (desktopPane.getHeight() - ef.getHeight()) / 2;
        ef.setLocation(Math.max(x, 0), Math.max(y, 0));
        ef.setVisible(true);
    }//GEN-LAST:event_EtudiantMenuItemActionPerformed

    private void byTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byTypeActionPerformed
        ByCompetitionType bct = new ByCompetitionType();
        desktopPane.add(bct);
        int x = (desktopPane.getWidth() - bct.getWidth()) / 2;
        int y = (desktopPane.getHeight() - bct.getHeight()) / 2;
        bct.setLocation(Math.max(x, 0), Math.max(y, 0));
        bct.setVisible(true);
    }//GEN-LAST:event_byTypeActionPerformed

    private void byNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byNameActionPerformed
        ByCompetitionName bcn = new ByCompetitionName();
        desktopPane.add(bcn);
        int x = (desktopPane.getWidth() - bcn.getWidth()) / 2;
        int y = (desktopPane.getHeight() - bcn.getHeight()) / 2;
        bcn.setLocation(Math.max(x, 0), Math.max(y, 0));
        bcn.setVisible(true);
    }//GEN-LAST:event_byNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CompetitionMenuItem;
    private javax.swing.JMenuItem EtudiantMenuItem;
    private javax.swing.JMenuItem byName;
    private javax.swing.JMenuItem byType;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listeEtdMenuItem;
    private javax.swing.JMenu listeMenuItem;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
